/* Caption engine: ~HAND handwritten captions plus 14 meme templates fed by word banks. */
(function () {
  'use strict';
  const pick = (a) => a[Math.floor(Math.random() * a.length)];

  const S = ["the build passes on the first try","someone says 'quick question'","the wifi dies mid-deploy","i see a 4000 line PR","the tests pass locally","the meeting could have been an email","prod goes down at 5pm","the intern merges to main","i find my own old code","the coffee machine is empty","i open the logs","the ai agrees with me","the ai disagrees with me","someone says 'it's a small change'","docker pull takes forever","the cert expires","i forgot to save","ctrl+s does nothing","the cron job fires at 3am","i hit 100 browser tabs","the backup actually restores","my code works and i don't know why","my code breaks and i don't know why","dns gets blamed","someone says 'just use kubernetes'","the pager goes off","the update bricks everything","the reviewer writes 'nit:'","it's friday 17:59","i see 'undefined'","my agent says 'done!'","the agent is not done","the router needs a reboot again","i find a todo from 2019","the repo has 900 open issues","the staging env is also prod","someone force-pushes to main","the build is red and nobody knows why","the fan gets loud","the disk is 99% full","the container restarts for no reason","the yaml has a tab in it","the readme is a lie","the dependency updates itself","i said 'i'll fix it later'","the mustache twitches","the eyebrows go up","the log says 'everything is fine'","i accidentally learn something","the swap is full again","someone asks for the roadmap","i get a notification at 3am","the plan survives contact with reality (it didn't)","an agent deletes the wrong branch","the free tier is over","i discover a new framework","my side project gets a star"];
  const R = ["smug orange noises","slurp.","one eyebrow rises 2mm","this is fine","calm. the mustache twitches","simply logs off","gunterlie sees all","pretends it was planned","opens a new terminal. new life","ships it anyway","blames dns","touches no grass. only keyboard","screams in orange","stares into the middle distance","unironically proud","tries again, same way, louder","accepts fate","orders more ram","adds another container","deletes the evidence","shrugs in yaml","sudo shrug","makes loud mustache sounds","goes feral","goblin mode engaged","ascends","does a little dance","reboots. hopes. reboots again","writes a 3 page postmortem about nothing","buys a new mini pc","turns the monitor off to feel safer","opens the editor like nothing happened","laughs in orange","goes full gigachad","hides under the desk","blames the cat","calls it a feature","whispers 'skill issue'","mutters 'it worked yesterday'","commits anyway"];
  const A = ["i'll sleep early tonight","just a quick fix","i'll document it later","no more side projects","i don't need another vm","i'll keep it simple","tonight i touch grass","i will not open the editor","i'm only checking one thing","i'll write tests first","i will not overengineer this","this is the last commit","i'm done with the homelab","i'll go to bed at ten","i'll read the docs first","one tab only","no more coffee","i'll update on a monday","small PR this time","i'm not touching the config","i'll just look at the logs","let's keep the scope small","i will say no to the new framework","this weekend i rest"];
  const B = ["it's 4am and the cluster has a new node","rewrites the whole thing in a new framework","documentation: ???","starts three side projects","spins up 6 vms","adds a message queue","i touched the terminal","opens the editor immediately","falls into a 5 hour rabbit hole","tests? later. vibes now","builds an abstraction for the abstraction","pushes 14 more commits","buys a new mini pc","it's 2am. the router is open","reads the source code instead","47 tabs","coffee #6","updates on a friday","4000 lines changed","adds a feature nobody asked for","migrates to rust for fun","refactors the refactor","opens a PR with no description","deploys on a friday","edits the config live","reorganizes the whole repo","installs a new tool, uses it once","learns a new language instead of sleeping"];
  const N = ["senior devs","juniors","the cron job","my brain","the build server","git history","my homelab","agents","node_modules","legacy code","my todo list","the pager","docker","dns","the reviewer","the intern","the weekend","my side projects","the staging env","the load balancer","the nas","my router","the changelog","the readme","the backlog","the monolith","the linter","the cache","the vpn","the mustache"];
  const BE = ["works. nobody knows why","silent until 3am","has one job. fails it","heavier than a black hole","a rumor of a plan","fixes nothing, adds 2 bugs","writes code, deletes code, repeats","has opinions about tabs","always one more thing","refuses to be restarted","feral and unmonitored","ships. regrets.","is a feature, officially","knows what you did last deploy","is fine. (it isn't)","has no logs, only vibes","is held together by hope","is mostly comments","is somehow still alive","has lore","has trust issues","does it all at 3am","gets worse when watched","is cursed. do not touch","is orange"];
  const O = ["ship on a friday","touch the config","restart the router at noon","update everything at once","read the changelog","explain the homelab to family","stop at one container","delete node_modules","rm -rf without crying","close 47 tabs","merge without a conflict","comment the code","name a variable well","estimate a task","leave a test flaky","unplug the nas","read the whole yaml","trust the cache","stay on topic","walk away from a bug","fix just one thing","use one monitor","reboot just once","skip the postmortem","answer 'quick question'","avoid the rabbit hole","say no to a new framework","stop at one tab"];
  const P = [["kubernetes","docker compose with a bigger budget"],["microservices","functions with network latency"],["the cloud","someone else's computer"],["ai","autocomplete with confidence"],["devops","ops with a rebrand"],["a monorepo","a very big folder"],["blockchain","a slow database"],["serverless","a server you can't see"],["agile","meetings with stickers"],["scrum","standups with extra steps"],["a homelab","a hobby that scales your power bill"],["yaml","json with shame"],["git","ctrl+z with feelings"],["prod","test with consequences"],["a feature","a bug with a pr"],["a framework","a library that got ideas"],["vibe coding","coding with extra anxiety"],["a rewrite","the same bugs, but new"],["the cloud bill","rent for a server you forgot"],["a cron job","a time bomb with a schedule"],["a backup","a hope with a timestamp"],["docker","a vm that's in denial"],["an agent","a for loop with an ego"],["monitoring","a dashboard of denial"],["a standup","a meeting for people who stand"],["an mvp","a prototype that never left"],["a hotfix","a bug with a head start"],["a pull request","an invitation to argue"],["tech debt","a loan at 40% apr"],["a reboot","a prayer in two parts"]];
  const X = [["tabs","spaces"],["vim","emacs"],["light mode","dark mode"],["cats","dogs"],["mac","linux"],["docker","vms"],["rest","graphql"],["monolith","microservices"],["sleep","one more commit"],["coffee","energy drink"],["friday","monday"],["prod","staging"],["plan","vibes"],["nas","cloud"],["ethernet","wifi"],["rust","python"],["ssh","gui"],["tests","hope"],["main","branch"],["bed","debugging"]];
  const Z = ["both","neither. orange","chaos","slurp","the third option: reboot","whichever has more mustache","vibes","delete both, start over","the one that is already broken","a nap","whatever ships faster","the one with the memes"];
  const C = ["the monday standup","the cert renewal","the friday deploy","the 3am page","the big update","the audit","the invoice","the dns outage","the merge conflict","the weekend of tinkering","the new framework","the reorg","gunterlie","the disk filling up","the yearly 'we should migrate'","the mandatory fun","the supply chain","the vendor lock-in","the roadmap meeting","the post-update reboot"];
  const SJ = ["me","gunterlie","my router","the cron job","the nas","my docker host","the agent","the mustache","the beard","the eyebrows","my homelab","the cat","the build server","the intern","the cache","the load balancer"];
  const W = ["orange noises","slurp slurp slurp","i want one more container","new vm who dis","rebooting for no reason","i will now fail silently","i have 400 opinions","what if we rewrote everything","gunterlie","loud mustache sounds","i'm bored, deleting stuff","i have become sentient (restart pending)","i'm calling it a feature","trust me, bro","i was never here","have you tried turning me off","i have no memory of this","what is a backup","i refuse","hold my yaml"];
  const NX = ["it's not a bug","it's not a hack","it's not tech debt","it's not a memory leak","it's not a crash","it's not procrastination","it's not a mess","it's not hoarding","it's not chaos","it's not a fire","it's not broken","it's not slow","it's not a cry for help","it's not a phase"];
  const NY = ["it's a feature","it's a lifestyle","it's a time capsule","it's a long-term cache","it's a surprise reboot","it's research","it's a system","it's a collection","it's art","it's a controlled burn","it's a vibe","it's thoughtfully paced","it's called lore","it's orange","it's a personality"];
  const IDA = ["test my code","read the docs","deploy on friday","back up","update","use git","write comments","close tabs","sleep","check the logs","read the error","ask for help","use a linter","name things well","touch grass","drink water"];
  const IDB = ["it's in production","it's an accident","i regret it instantly","it's at 4am","it's by accident and it works","i have no logs","i'm orange","i blame dns","gunterlie approves","it's all at once","it's with confidence","i do it twice","it breaks","it somehow works","i tell nobody","nobody believes me"];
  const PV = ["you opened the logs","you said 'quick fix' out loud","you pushed to main on a friday","you hear 'can we jump on a call'","the mustache looks at you","you mistook prod for dev","you have 14 containers and no plan","it's 3am and the pipeline is red","you just remembered the backup","you didn't make a backup","the agent says 'all done!'","the eyebrow rises","you've been asked to 'just add a button'","the nas starts clicking","the fan spins up","you see 'rebase' in the PR title"];
  const EX = ["my homelab","my side project","my setup","the yaml","the plan","my backup strategy","my git workflow","my 47 tabs","the architecture","my cron jobs","my dotfiles","why it needs 12 containers"];
  const TO = ["my family","the cat","a rubber duck","the void","hr","my past self","a reviewer","the ai","the intern","my landlord","gunterlie","a very patient friend","the router","my mom"];
  const T = ["3am","4am","2am","5am","midnight","friday 17:59","monday 9:01","sunday night","the weekend","lunch","a normal tuesday"];
  const D = ["and i'm reorganizing the yaml","and i just had a great idea","and the server is up. i'm not","and the agent is still going","and nobody asked me to do this","and i'm learning rust now","and i have bought a new mini pc","and i'm rewriting the readme","and the pipeline is red","and gunterlie is thriving","and i'm watching logs scroll","and i'm sure it's dns","and i'm on the 6th coffee","and it's working. suspicious","and i'm adding one tiny feature","and i just wrote 'fix' as a commit message"];

  const fam = [
    () => ["when " + pick(S), pick(R)],
    () => ["me: " + pick(A), "also me: " + pick(B)],
    () => [pick(N) + " be like", pick(BE)],
    () => ["one does not simply", pick(O)],
    () => { const p = pick(P); return [p[0], "is just " + p[1] + " with extra steps"]; },
    () => { const x = pick(X); return [x[0] + " vs " + x[1], "gunterlie picks " + pick(Z)]; },
    () => ["brace yourselves", pick(C) + " is coming"],
    () => ["nobody:", pick(SJ) + ": " + pick(W)],
    () => [pick(NX), pick(NY)],
    () => ["i don't always " + pick(IDA), "but when i do, " + pick(IDB)],
    () => ["pov:", pick(PV)],
    () => ["me explaining " + pick(EX), "to " + pick(TO)],
    () => ["it's " + pick(T), pick(D)],
    () => ["gunterlie when " + pick(S), pick(R)],
  ];
  const sizes = [S.length*R.length, A.length*B.length, N.length*BE.length, O.length, P.length, X.length*Z.length, C.length, SJ.length*W.length, NX.length*NY.length, IDA.length*IDB.length, PV.length, EX.length*TO.length, T.length*D.length, S.length*R.length];
  const HAND = [
    ['when the build passes', "but you didn't change anything"],
    ['one does not simply', 'ship on a friday'],
    ['it works on my machine', 'so we shipped my machine'],
    ['what did you expect?', 'gunterlie'],
    ["i'll just fix one thing", 'also me: 14 new containers'],
    ['i asked for a small pr', 'the diff: 4,000 lines'],
    ['slurp', 'slurp slurp'],
    ['no regressions', 'famous last words'],
    ['404', 'sleep not found'],
    ['they said touch grass', 'i touched the terminal'],
    ['me: i need a plan', 'also me: vibes'],
    ['orange guy', 'smug guy'],
    ['its not a bug', 'its a feature with attitude'],
    ['merge conflict?', 'i hardly know her'],
    ["me explaining the plan", "the plan: vibes"],
    ["reviewer: any concerns?", "me: several, all of them mine"],
    ["fixed one bug", "found three friends"],
    ["i'll sleep early tonight", "it is 4am. the container is up"],
    ["just one more commit", "sunrise"],
    ["it compiles", "ship it"],
    ["the tests are green", "because i deleted the tests"],
    ["senior dev energy", "turn it off and on again"],
    ["git blame", "oh no. it's me"],
    ["works in dev", "prod has entered the chat"],
    ["we have a backup", "do we restore it? never tried"],
    ["monday morning", "the pipeline has opinions"],
    ["me: small refactor", "the repo: who are you"],
    ["i read the docs", "the docs lied"],
    ["is it dns?", "it's always dns"],
    ["is it dns?", "no. it was dns"],
    ["todo: fix later", "later: never"],
    ["temporary workaround", "since 2019"],
    ["it's just a quick script", "300 lines and a cron job"],
    ["hello world", "goodbye weekend"],
    ["my code", "a mystery, even to me"],
    ["rubber duck", "never speaks, always judges"],
    ["this is fine", "the logs: on fire"],
    ["ctrl+z", "ctrl+z. ctrl+z. oh no"],
    ["ai wrote this", "i take full credit"],
    ["prompt: be careful", "ai: i deleted prod, carefully"],
    ["vibe coding", "vibe debugging"],
    ["one more agent", "and one more agent"],
    ["too many tabs", "no regrets, only tabs"],
    ["i have a system", "the system: 47 sticky notes"],
    ["orange you glad", "i didn't say banana"],
    ["ginger power", "unlimited, unbothered"],
    ["stand back", "i'm about to touch the config"],
    ["sudo make me a sandwich", "okay"],
    ["rm -rf", "is a lifestyle"],
    ["boss: can you quickly", "me: define quickly"],
    ["estimate: two hours", "reality: two weekends"],
    ["reading the changelog", "reading the whole changelog"],
    ["he's not a bug", "he's a feature request"],
    ["zero days since", "the last 'quick' fix"],
    ["i accept your offer", "to touch grass. later"],
    ["delete the cache", "and cry"],
    ["did you try turning it off", "yes. and on. and off"],
    ["wifi works", "i fear what changed"],
    ["average gunterlie enjoyer", "chronically orange"],
    ["me, a smart man", "also me, rebooting the router"],
    ["gunterlie", "has entered the chat"],
    ["welcome to", "the orange zone"],
    ["you've been", "gunterlie'd"],
    ["so it begins", "slurp"],
    ["slurp slurp slurp", "slurp"],
    ["nobody:", "gunterlie: slurp"],
    ["breaking news", "orange man is smug"],
    ["press f", "to pay respects to the build"],
    ["bitcoin", "gunterlie coin: priceless"],
    ["kernel panic", "gunterlie: don't panic"],
    ["stack overflow", "my one true friend"],
    ["merge to main", "pray"],
    ["friday 17:59", "i have one small change"],
    ["it said 'are you sure?'", "i was not sure. i clicked yes"],
    ["i don't always test", "but when i do, it's in prod"],
    ["my toaster", "now runs docker"],
    ["my homelab", "is a cry for help"],
    ["more ram", "less problems (lie)"],
    ["swap is full", "so is my heart"],
    ["new container", "who dis"],
    ["the nas said no", "the nas is always right"],
    ["one does not simply", "turn off the light and leave"],
    ["brace yourselves", "gunterlie is coming"],
    ["hold my coffee", "i'm about to push"],
    ["success", "is just failure, but orange"],
    ["sleep", "is for the merged"],
    ["trust me", "i'm an orange man"],
    ["i've seen things", "in the dependency tree"],,
    ["the 5 stages of debugging", "denial, anger, bargaining, print statements, acceptance"],
    ["my sleep schedule", "a rumor"],
    ["lets keep it simple", "adds a message queue"],
    ["me reading my own code", "who wrote this garbage / me, last year"],
    ["senior engineer", "googles it like everyone else"],
    ["junior engineer", "googles it faster"],
    ["the intern", "deleted prod. a legend"],
    ["works on my machine", "ship the machine"],
    ["the pull request", "47 files changed, no description"],
    ["lgtm", "did not read"],
    ["approved", "in spirit"],
    ["quick sync?", "it was not quick"],
    ["this could have been an email", "it was a 2 hour meeting"],
    ["per my last email", "please look at my last email"],
    ["circling back", "never heard from again"],
    ["we need to talk about", "the cron job"],
    ["who touched the config", "everyone, nobody, the cat"],
    ["rolling back", "rolling back the rollback"],
    ["hotfix on a friday", "hope is not a strategy"],
    ["cloud costs", "my wallet has left the chat"],
    ["serverless", "there is a server, i just cannot see it"],
    ["microservices", "now i have 40 problems in 40 places"],
    ["kubernetes", "a cry for help in yaml"],
    ["yaml", "indentation is a lifestyle"],
    ["regex", "now i have two problems"],
    ["javascript", "[] + {} = ???"],
    ["css", "why is it centered. why is it not centered"],
    ["tabs vs spaces", "gunterlie vs the world"],
    ["vim", "how do i exit this"],
    ["emacs", "an os with a text editor"],
    ["rust", "borrow checker says no"],
    ["python", "import antigravity"],
    ["php", "still alive, still weird"],
    ["docker", "works. don't touch. never touch"],
    ["docker compose up", "and pray to the port numbers"],
    ["port 8080", "already in use. always in use"],
    ["localhost", "there is no place like it"],
    ["it's not a memory leak", "it's a long-term cache"],
    ["it's not slow", "it's thoughtfully paced"],
    ["it's not a bug", "the spec was a suggestion"],
    ["technical debt", "compounding at 40% apr"],
    ["one line change", "breaks 12 tests"],
    ["fixed the tests", "by changing the tests"],
    ["deleted 400 lines", "everything works better"],
    ["added 400 lines", "nothing works"],
    ["commit message:", "fix. fix again. final fix. final final"],
    ["git push --force", "and just like that, nobody is happy"],
    ["git stash", "never seen again"],
    ["detached head", "the story of my life"],
    ["merge commit", "history is a flat circle"],
    ["the build is red", "blame the weather"],
    ["the build is green", "blame the cache"],
    ["flaky test", "the only honest test"],
    ["unit tests", "passed. integration tests: cry"],
    ["works at 3am", "breaks at 9am"],
    ["it's the weekend", "the pager disagrees"],
    ["on call tonight", "sleep is a social construct"],
    ["the incident report", "a story with no villains, only vibes"],
    ["postmortem", "we should have had a backup. we did not"],
    ["50% of my job", "knowing which logs to ignore"],
    ["the logs say", "everything is fine"],
    ["the logs also say", "everything is on fire"],
    ["did you read the error?", "it's in english"],
    ["the error message", "helpfully says 'error'"],
    ["404 not found", "404 hope not found"],
    ["500 internal server error", "500 internal feelings error"],
    ["418 i'm a teapot", "a status code with dreams"],
    ["it was dns", "it was always dns"],
    ["it was certificates", "it was the expired certificate"],
    ["it was the cache", "clear it. clear it again"],
    ["have you tried", "unplugging it from the wall"],
    ["this is fine", "*the whole rack is on fire*"],
    ["the cat walked on", "the keyboard. and deployed"],
    ["my plant", "has better uptime than my server"],
    ["my server", "is a potato with ambition"],
    ["my other server", "is also a potato"],
    ["sata cable", "the real single point of failure"],
    ["the nas is quiet", "too quiet"],
    ["homelab", "an expensive way to say 'i have a hobby'"],
    ["just one more vm", "just one more vm"],
    ["one more node", "my power bill: sir please"],
    ["the switch", "is warm. it's fine. it's fine"],
    ["firmware update", "brave"],
    ["bios update", "braver"],
    ["never update on friday", "never update at all"],
    ["update available", "ignore"],
    ["update installed", "why is everything different"],
    ["turn it off and on again", "a spell as old as time"],
    ["the cloud", "is just someone else's homelab"],
    ["my backups", "are in the cloud. the cloud is me"],
    ["restore test", "never. we trust the vibes"],
    ["raid is not a backup", "raid: i'm in danger"],
    ["3-2-1 backup rule", "3 copies, 2 formats, 1 prayer"],
    ["monitoring", "a pretty dashboard of denial"],
    ["alert fatigue", "mute the channel, sleep at night"],
    ["ai agent", "deleted my branch with confidence"],
    ["ai says", "i'm 95% sure. i am 100% wrong"],
    ["prompt engineering", "please. please. i'm begging you"],
    ["hallucination", "it's creative, not wrong"],
    ["context window", "full. as usual"],
    ["tokens", "where did they all go"],
    ["temperature 0", "still invents things"],
    ["agentic", "it just does things. scary things"],
    ["vibes only", "no tests. no plan. just orange"],
    ["ship fast", "fix later. pray often"],
    ["move fast", "break things. gunterlie fixes"],
    ["done", "never done. just abandoned"],
    ["mvp", "minimum viable plan: panic"],
    ["roadmap", "a work of fiction"],
    ["sprint planning", "the dream before the nightmare"],
    ["standup", "i did a thing. i will do another thing"],
    ["retro", "we should communicate better (we won't)"],
    ["backlog", "nobody has read past item 12"],
    ["priority: low", "priority: forgotten"],
    ["priority: urgent", "priority: i already did it"],
    ["estimates", "lies we tell to feel organized"],
    ["jira", "a tool of mild suffering"],
    ["slack", "where productivity goes to chat"],
    ["the notification", "it was a sticker"],
    ["@here", "it was not urgent"],
    ["mute channel", "ah. peace"],
    ["dark mode", "my eyes will survive another day"],
    ["light mode", "a bold lifestyle choice"],
    ["dad jokes", "but make them orange"],
    ["orange juice", "the fuel of memelords"],
    ["carrot", "a distant cousin"],
    ["traffic cone", "my emotional support animal"],
    ["pumpkin", "seasonal gunterlie"],
    ["fire hydrant", "orange. alert. ready"],
    ["cheeto dust", "on the keyboard. again"],
    ["the sun at 5pm", "gunterlie at all times"],
    ["the one and only", "orange man of memes"],
    ["the legend", "the myth. the mustache"],
    ["mustache power", "activate"],
    ["beard check", "passed"],
    ["hair check", "chaotic. as intended"],
    ["eyebrows", "doing a lot of work today"],
    ["raised eyebrow", "the final boss of code review"],
    ["smug level", "maximum"],
    ["who asked", "me. i asked. i always ask"],
    ["touch grass", "touch grass, they said. it was orange"],
    ["no thoughts", "only orange"],
    ["head empty", "only slurp"],
    ["brain: 1%", "memes: 99%"],
    ["buffering", "please wait. the meme is loading"],
    ["loading", "...still loading"],
    ["please wait", "the orange is coming"],
    ["error 500", "memes unavailable. try again"],
    ["low battery", "and it's 3 in the morning"],
    ["out of coffee", "out of ideas. out of time"],
    ["it's coffee o'clock", "always"],
    ["decaf", "the real villain"],
    ["big brain", "small deadline"],
    ["galaxy brain", "ships it anyway"],
    ["infinite loop", "a hobby"],
    ["undefined", "is not a function. neither am i"],
    ["null", "nothing. lovely"],
    ["segfault", "core dumped. so am i"],
    ["off by one", "story of my life"],
    ["hello world", "goodbye sanity"]
  ];
  window.CAPTION_COUNT = HAND.length + sizes.reduce((a, b) => a + b, 0);
  window.CAPTIONS = HAND;
  window.makeCaption = () => Math.random() < .3 ? pick(HAND) : pick(fam)();
})();
